import { CAPICOM_STORE_LOCATION } from './CAPICOM_STORE_LOCATION';

export const enum CADESCOM_STORE_LOCATION {
    CAPICOM_LOCAL_MACHINE_STORE = CAPICOM_STORE_LOCATION.CAPICOM_LOCAL_MACHINE_STORE,
    CAPICOM_CURRENT_USER_STORE = CAPICOM_STORE_LOCATION.CAPICOM_CURRENT_USER_STORE,
    CADESCOM_CONTAINER_STORE = 100,
}
