export const enum CAPICOM_STORE_OPEN_MODE {
    CAPICOM_STORE_OPEN_READ_ONLY = 0,
    CAPICOM_STORE_OPEN_READ_WRITE = 1,
    CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED = 2,

    CAPICOM_STORE_OPEN_EXISTING_ONLY = 128,
    CAPICOM_STORE_OPEN_INCLUDE_ARCHIVED = 256,
}
