export const enum CAPICOM_CERT_INFO_TYPE {
    CAPICOM_CERT_INFO_SUBJECT_SIMPLE_NAME = 0,
    CAPICOM_CERT_INFO_ISSUER_SIMPLE_NAME = 1,
    CAPICOM_CERT_INFO_SUBJECT_EMAIL_NAME = 2,
    CAPICOM_CERT_INFO_ISSUER_EMAIL_NAME = 3,
    CAPICOM_CERT_INFO_SUBJECT_UPN = 4,
    CAPICOM_CERT_INFO_ISSUER_UPN = 5,
    CAPICOM_CERT_INFO_SUBJECT_DNS_NAME = 6,
    CAPICOM_CERT_INFO_ISSUER_DNS_NAME = 7,
}
