export const enum CAPICOM_CHECK_FLAG {
    CAPICOM_CHECK_NONE = 0x0000,
    CAPICOM_CHECK_TRUSTED_ROOT = 0x0001,
    CAPICOM_CHECK_TIME_VALIDITY = 0x0002,
    CAPICOM_CHECK_SIGNATURE_VALIDITY = 0x0004,
    CAPICOM_CHECK_ONLINE_REVOCATION_STATUS = 0x0008,
    CAPICOM_CHECK_OFFLINE_REVOCATION_STATUS = 0x0010,
    CAPICOM_CHECK_COMPLETE_CHAIN = 0x0020,
    CAPICOM_CHECK_NAME_CONSTRAINTS = 0x0040,
    CAPICOM_CHECK_BASIC_CONSTRAINTS = 0x0080,
    CAPICOM_CHECK_NESTED_VALIDITY_PERIOD = 0x0100,

    CAPICOM_CHECK_ONLINE_ALL = CAPICOM_CHECK_TRUSTED_ROOT | // 0x01EF,
        CAPICOM_CHECK_TIME_VALIDITY |
        CAPICOM_CHECK_SIGNATURE_VALIDITY |
        CAPICOM_CHECK_ONLINE_REVOCATION_STATUS |
        CAPICOM_CHECK_COMPLETE_CHAIN |
        CAPICOM_CHECK_NAME_CONSTRAINTS |
        CAPICOM_CHECK_BASIC_CONSTRAINTS |
        CAPICOM_CHECK_NESTED_VALIDITY_PERIOD,

    CAPICOM_CHECK_OFFLINE_ALL = CAPICOM_CHECK_TRUSTED_ROOT | // 0x01f7,
    CAPICOM_CHECK_TIME_VALIDITY |
    CAPICOM_CHECK_SIGNATURE_VALIDITY |
    CAPICOM_CHECK_OFFLINE_REVOCATION_STATUS |
    CAPICOM_CHECK_COMPLETE_CHAIN |
    CAPICOM_CHECK_NAME_CONSTRAINTS |
    CAPICOM_CHECK_BASIC_CONSTRAINTS |
    CAPICOM_CHECK_NESTED_VALIDITY_PERIOD,
}
