import * as Sync from '../interfaces.sync/@';
import * as Async from '../interfaces.async/@';

// CAPICOM
export declare function isAsync(obj: Sync.IBasicConstraints | Async.IBasicConstraints): obj is Async.IBasicConstraints;
export declare function isAsync(obj: Sync.ICertificate | Async.ICertificate): obj is Async.ICertificate;
export declare function isAsync(obj: Sync.ICertificate2 | Async.ICertificate2): obj is Async.ICertificate2;
export declare function isAsync(obj: Sync.ICertificates | Async.ICertificates): obj is Async.ICertificates;
export declare function isAsync(obj: Sync.ICertificateStatus | Async.ICertificateStatus): obj is Async.ICertificateStatus;
export declare function isAsync(obj: Sync.IEKU | Async.IEKU): obj is Async.IEKU;
export declare function isAsync(obj: Sync.IEKUs | Async.IEKUs): obj is Async.IEKUs;
export declare function isAsync(obj: Sync.IEncodedData | Async.IEncodedData): obj is Async.IEncodedData;
export declare function isAsync(obj: Sync.IEnvelopedData | Async.IEnvelopedData): obj is Async.IEnvelopedData;
export declare function isAsync(obj: Sync.IExtendedKeyUsage | Async.IExtendedKeyUsage): obj is Async.IExtendedKeyUsage;
export declare function isAsync(obj: Sync.IHashedData | Async.IHashedData): obj is Async.IHashedData;
export declare function isAsync(obj: Sync.IKeyUsage | Async.IKeyUsage): obj is Async.IKeyUsage;
export declare function isAsync(obj: Sync.IOID | Async.IOID): obj is Async.IOID;
export declare function isAsync(obj: Sync.IPrivateKey | Async.IPrivateKey): obj is Async.IPrivateKey;
export declare function isAsync(obj: Sync.IPublicKey | Async.IPublicKey): obj is Async.IPublicKey;
export declare function isAsync(obj: Sync.ISignedData | Async.ISignedData): obj is Async.ISignedData;
export declare function isAsync(obj: Sync.ISigner | Async.ISigner): obj is Async.ISigner;
export declare function isAsync(obj: Sync.ISigners | Async.ISigners): obj is Async.ISigners;
export declare function isAsync(obj: Sync.IStore | Async.IStore): obj is Async.IStore;

// CAdESCOM
export declare function isAsync(obj: Sync.IAbout | Async.IAbout): obj is Async.IAbout;
export declare function isAsync(obj: Sync.IAbout3 | Async.IAbout3): obj is Async.IAbout3;
export declare function isAsync(obj: Sync.IAbout4 | Async.IAbout4): obj is Async.IAbout4;
export declare function isAsync(obj: Sync.ICPAttribute | Async.ICPAttribute): obj is Async.ICPAttribute;
export declare function isAsync(obj: Sync.ICPAttribute2 | Async.ICPAttribute2): obj is Async.ICPAttribute2;
export declare function isAsync(obj: Sync.ICPAttributes | Async.ICPAttributes): obj is Async.ICPAttributes;
export declare function isAsync(obj: Sync.ICPBlobs | Async.ICPBlobs): obj is Async.ICPBlobs;
export declare function isAsync(obj: Sync.ICPCertificate | Async.ICPCertificate): obj is Async.ICPCertificate;
export declare function isAsync(obj: Sync.ICPEnvelopedData | Async.ICPEnvelopedData): obj is Async.ICPEnvelopedData;
export declare function isAsync(obj: Sync.ICPEnvelopedData2 | Async.ICPEnvelopedData2): obj is Async.ICPEnvelopedData2;
export declare function isAsync(obj: Sync.ICPHashedData | Async.ICPHashedData): obj is Async.ICPHashedData;
export declare function isAsync(obj: Sync.ICPPrivateKey | Async.ICPPrivateKey): obj is Async.ICPPrivateKey;
export declare function isAsync(obj: Sync.ICPSignedData | Async.ICPSignedData): obj is Async.ICPSignedData;
export declare function isAsync(obj: Sync.ICPSignedData2 | Async.ICPSignedData2): obj is Async.ICPSignedData2;
export declare function isAsync(obj: Sync.ICPSignedData3 | Async.ICPSignedData3): obj is Async.ICPSignedData3;
export declare function isAsync(obj: Sync.ICPSignedData4 | Async.ICPSignedData4): obj is Async.ICPSignedData4;
export declare function isAsync(obj: Sync.ICPSignedData5 | Async.ICPSignedData5): obj is Async.ICPSignedData5;
export declare function isAsync(obj: Sync.ICPSigner | Async.ICPSigner): obj is Async.ICPSigner;
export declare function isAsync(obj: Sync.ICPSigner2 | Async.ICPSigner2): obj is Async.ICPSigner2;
export declare function isAsync(obj: Sync.ICPSigner3 | Async.ICPSigner3): obj is Async.ICPSigner3;
export declare function isAsync(obj: Sync.ICPSigner4 | Async.ICPSigner4): obj is Async.ICPSigner4;
export declare function isAsync(obj: Sync.ICPSigner5 | Async.ICPSigner5): obj is Async.ICPSigner5;
export declare function isAsync(obj: Sync.ICPSigner6 | Async.ICPSigner6): obj is Async.ICPSigner6;
export declare function isAsync(obj: Sync.IRawSignature | Async.IRawSignature): obj is Async.IRawSignature;
export declare function isAsync(obj: Sync.ISignatureStatus | Async.ISignatureStatus): obj is Async.ISignatureStatus;
export declare function isAsync(obj: Sync.ISignedXML | Async.ISignedXML): obj is Async.ISignedXML;
export declare function isAsync(obj: Sync.ISymmetricAlgorithm | Async.ISymmetricAlgorithm): obj is Async.ISymmetricAlgorithm;
export declare function isAsync(obj: Sync.IVersion | Async.IVersion): obj is Async.IVersion;
export declare function isAsync(obj: Sync.IWebClassFactory | Async.IWebClassFactory): obj is Async.IWebClassFactory;
