import * as Sync from '../interfaces.sync/@';
import * as Async from '../interfaces.async/@';

// CAPICOM
export declare function isSync(obj: Sync.IBasicConstraints | Async.IBasicConstraints): obj is Sync.IBasicConstraints;
export declare function isSync(obj: Sync.ICertificate | Async.ICertificate): obj is Sync.ICertificate;
export declare function isSync(obj: Sync.ICertificate2 | Async.ICertificate2): obj is Sync.ICertificate2;
export declare function isSync(obj: Sync.ICertificates | Async.ICertificates): obj is Sync.ICertificates;
export declare function isSync(obj: Sync.ICertificateStatus | Async.ICertificateStatus): obj is Sync.ICertificateStatus;
export declare function isSync(obj: Sync.IEKU | Async.IEKU): obj is Sync.IEKU;
export declare function isSync(obj: Sync.IEKUs | Async.IEKUs): obj is Sync.IEKUs;
export declare function isSync(obj: Sync.IEncodedData | Async.IEncodedData): obj is Sync.IEncodedData;
export declare function isSync(obj: Sync.IEnvelopedData | Async.IEnvelopedData): obj is Sync.IEnvelopedData;
export declare function isSync(obj: Sync.IExtendedKeyUsage | Async.IExtendedKeyUsage): obj is Sync.IExtendedKeyUsage;
export declare function isSync(obj: Sync.IHashedData | Async.IHashedData): obj is Sync.IHashedData;
export declare function isSync(obj: Sync.IKeyUsage | Async.IKeyUsage): obj is Sync.IKeyUsage;
export declare function isSync(obj: Sync.IOID | Async.IOID): obj is Sync.IOID;
export declare function isSync(obj: Sync.IPrivateKey | Async.IPrivateKey): obj is Sync.IPrivateKey;
export declare function isSync(obj: Sync.IPublicKey | Async.IPublicKey): obj is Sync.IPublicKey;
export declare function isSync(obj: Sync.ISignedData | Async.ISignedData): obj is Sync.ISignedData;
export declare function isSync(obj: Sync.ISigner | Async.ISigner): obj is Sync.ISigner;
export declare function isSync(obj: Sync.ISigners | Async.ISigners): obj is Sync.ISigners;
export declare function isSync(obj: Sync.IStore | Async.IStore): obj is Sync.IStore;

// CAdESCOM
export declare function isSync(obj: Sync.IAbout | Async.IAbout): obj is Sync.IAbout;
export declare function isSync(obj: Sync.IAbout3 | Async.IAbout3): obj is Sync.IAbout3;
export declare function isSync(obj: Sync.IAbout4 | Async.IAbout4): obj is Sync.IAbout4;
export declare function isSync(obj: Sync.ICPAttribute | Async.ICPAttribute): obj is Sync.ICPAttribute;
export declare function isSync(obj: Sync.ICPAttribute2 | Async.ICPAttribute2): obj is Sync.ICPAttribute2;
export declare function isSync(obj: Sync.ICPAttributes | Async.ICPAttributes): obj is Sync.ICPAttributes;
export declare function isSync(obj: Sync.ICPBlobs | Async.ICPBlobs): obj is Sync.ICPBlobs;
export declare function isSync(obj: Sync.ICPCertificate | Async.ICPCertificate): obj is Sync.ICPCertificate;
export declare function isSync(obj: Sync.ICPEnvelopedData | Async.ICPEnvelopedData): obj is Sync.ICPEnvelopedData;
export declare function isSync(obj: Sync.ICPEnvelopedData2 | Async.ICPEnvelopedData2): obj is Sync.ICPEnvelopedData2;
export declare function isSync(obj: Sync.ICPHashedData | Async.ICPHashedData): obj is Sync.ICPHashedData;
export declare function isSync(obj: Sync.ICPPrivateKey | Async.ICPPrivateKey): obj is Sync.ICPPrivateKey;
export declare function isSync(obj: Sync.ICPSignedData | Async.ICPSignedData): obj is Sync.ICPSignedData;
export declare function isSync(obj: Sync.ICPSignedData2 | Async.ICPSignedData2): obj is Sync.ICPSignedData2;
export declare function isSync(obj: Sync.ICPSignedData3 | Async.ICPSignedData3): obj is Sync.ICPSignedData3;
export declare function isSync(obj: Sync.ICPSignedData4 | Async.ICPSignedData4): obj is Sync.ICPSignedData4;
export declare function isSync(obj: Sync.ICPSignedData5 | Async.ICPSignedData5): obj is Sync.ICPSignedData5;
export declare function isSync(obj: Sync.ICPSigner | Async.ICPSigner): obj is Sync.ICPSigner;
export declare function isSync(obj: Sync.ICPSigner2 | Async.ICPSigner2): obj is Sync.ICPSigner2;
export declare function isSync(obj: Sync.ICPSigner3 | Async.ICPSigner3): obj is Sync.ICPSigner3;
export declare function isSync(obj: Sync.ICPSigner4 | Async.ICPSigner4): obj is Sync.ICPSigner4;
export declare function isSync(obj: Sync.ICPSigner5 | Async.ICPSigner5): obj is Sync.ICPSigner5;
export declare function isSync(obj: Sync.ICPSigner6 | Async.ICPSigner6): obj is Sync.ICPSigner6;
export declare function isSync(obj: Sync.IRawSignature | Async.IRawSignature): obj is Sync.IRawSignature;
export declare function isSync(obj: Sync.ISignatureStatus | Async.ISignatureStatus): obj is Sync.ISignatureStatus;
export declare function isSync(obj: Sync.ISignedXML | Async.ISignedXML): obj is Sync.ISignedXML;
export declare function isSync(obj: Sync.ISymmetricAlgorithm | Async.ISymmetricAlgorithm): obj is Sync.ISymmetricAlgorithm;
export declare function isSync(obj: Sync.IVersion | Async.IVersion): obj is Sync.IVersion;
export declare function isSync(obj: Sync.IWebClassFactory | Async.IWebClassFactory): obj is Sync.IWebClassFactory;
